### ISSUE TITLE
Smart signals "Not detected" for all entries.

### ISSUE THREAD

**Issue by stevezau** [fingerprintjs/fingerprintjs-pro-use-cases#131]
Hello,

I've been experimenting with Fingerprints through this sample application.

When I launched the app, I noticed that the "smart signals" table within the "Playground" section of the demo indicates "Not detected" for all entries. **I would have expected at least the geolocation to show.** 

![image](https://github.com/fingerprintjs/fingerprintjs-pro-use-cases/assets/6075483/7c73e6da-fac8-4ae6-b38b-6f164e592cda)

I made a comparison between the JSON output from the online demo (accessible at https://demo.fingerprint.com/playground) and my local version. It appears that the ipLocation data is present in two locations within the online demo:

- products.identification.data.ipLocation
- products.ipInfo.data.v4

Conversely, in my local demo, the IP address information is only found in:
- products.ipInfo.data.v4

This discrepancy seems to be the reason why the smart signals feature isn't displaying as expected.

I was going to submit a PR to resolve the issue but I didn't because I'm uncertain about the root cause of this issue. I am guessing It could be due to a missing setting/flag on my tenant or the possibility that the online demo uses a different version of the API. Regardless, it appears there's an issue with using this sample app, OOTB, with a fingerprint trial.

**Comment by stevezau** [comment]
Ahh.. According to the docs 

```This field is deprecated and will not return a result for applications created after January 23rd, 2024. See [IP Geolocation](https://dev.fingerprint.com/docs/smart-signals-overview#ip-geolocation) for a replacement available in our Smart Signals product.```

**Comment by makma** [comment]
Hey @stevezau! Thank you for noticing and letting us know. You've correctly identified the root cause of this issue. To avoid possible confusion, I believe the demo should also fallback to the new data contract if the info is missing in the Server API response. Feel free to submit a PR if you have space for that. If not, ccing @JuroUhlar , to bring this to his attention.

Thank you!

**Comment by JuroUhlar** [comment]
@stevezau Thanks a lot for spotting this bug! Here is a proposed fix: https://github.com/fingerprintjs/fingerprintjs-pro-use-cases/pull/132 
Let me know if you would prefer to submit your own PR instead, you are welcome to do so! If not, we will merge this shortly.

**Comment by stevezau** [comment]
@JuroUhlar looks good to me, exactly how i fixed it in my local env.
