### ISSUE TITLE
Introduce tests

### ISSUE THREAD

**Issue by TheUnderScorer** [fingerprintjs/fingerprintjs-pro-use-cases#41]
In this recent PR https://github.com/fingerprintjs/fingerprintjs-pro-use-cases/pull/40 we've introduced unit tests setup using vitest. It would be good to introduce some basic unit tests for the core logic of this project, especially in files stored in `/server` directory.

Furthermore, we could also introduce some basic [E2E tests](https://nextjs.org/docs/testing) that test at least all the "happy paths" of our examples.

**Comment by JuroUhlar** [comment]
We now have Playwright tests covering all use cases, closing
